import com.google.gson.JsonParser
import org.gradle.api.Plugin
import org.gradle.api.Project
import java.io.File
import java.net.URI
import java.util.*

//I think usable is ok
open class FetchVersionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        target.gradle.beforeProject {
            if (target.rootProject == target) {
                val prop = Properties()
                val theFile = File("gradle.properties")

                if (!theFile.exists()) {
                    return@beforeProject
                }

                if (target.gradle.startParameter.isOffline) {
                    return@beforeProject
                }

                val cacheFile = File(project.layout.buildDirectory.get().asFile, "dependency_sync.cache")
                if (!cacheFile.exists()) {
                    cacheFile.parentFile.mkdirs()
                    cacheFile.createNewFile()
                }

                prop.load(theFile.reader())

                val str = cacheFile.readLines(Charsets.UTF_8)
                if (!str.isEmpty()) {
                    if (str[0] == prop["minecraft_version"]) {
                        return@beforeProject
                    }
                }

                target.gradle.startParameter.isRefreshDependencies = true

                prop["fabric_version"] = getLatestModrinthVersion("fabric-api", target)
                prop["fabric_loader_version"] = getLatestFabricLoaderVersion()
                prop["neo_version"] = getLatestNeoForgeVersion(target)
                prop["cloth_config_version"] = getLatestModrinthVersion("cloth-config", target)!!.split("+")[0]
                prop["modmenu_version"] = getLatestModrinthVersion("modmenu", target)
                prop["neogradle.subsystems.parchment.mappingsVersion"] = getLatestParchmentVersion(target)
                prop["neogradle.subsystems.parchment.minecraftVersion"] = prop["minecraft_version"]

                prop.store(theFile.writer(Charsets.UTF_8), "Generated by fetchVersions task")

                cacheFile.setWritable(true)
                cacheFile.writeText(prop["minecraft_version"]!! as String, Charsets.UTF_8)
            }
        }
    }

    fun getLatestModrinthVersion(modId: String, project: Project): String? {
        val apiUrl = "https://api.modrinth.com/v2/project/$modId/version"
        val json = JsonParser.parseReader(URI(apiUrl).toURL().openStream().reader()).asJsonArray

        return json
            .filter {
                it.asJsonObject["game_versions"].asJsonArray.any { v -> v.asString == project.properties["minecraft_version"]!! }
            }
            .maxByOrNull {
                it.asJsonObject["date_published"].asString
            }
            ?.asJsonObject
            ?.get("version_number")
            ?.asString
    }

    fun getLatestParchmentVersion(project: Project): String {
        val mcVersion = project.properties["minecraft_version"]
        val baseUrl = "https://ldtteam.jfrog.io/artifactory/api/storage/parchmentmc-public/org/parchmentmc/data/parchment-$mcVersion/"
        val json = try {
            URI(baseUrl).toURL().readText()
        } catch (e: Exception) {
            throw RuntimeException(e)
        }

        val ele = JsonParser.parseString(json)
        val list = ele.asJsonObject["children"].asJsonArray.toList().map {
            it.asJsonObject
        }

        for (l in list) {
            val url = l.get("uri").asString
            val folder = l.get("folder").asBoolean

            if (!folder) {
                continue
            }

            if (url.endsWith("-SNAPSHOT")) {
                continue
            }

            val latest = url.substring(1)
            return latest
        }

        throw RuntimeException("No Parchment data found for $mcVersion")
    }

    fun getLatestFabricLoaderVersion(): String? {
        val url = URI("https://meta.fabricmc.net/v2/versions/loader").toURL()
        val json = JsonParser.parseReader(url.openStream().reader()).asJsonArray

        return json.firstOrNull {
            it.asJsonObject["stable"].asBoolean
        }?.asJsonObject?.get("version")?.asString
    }

    fun getLatestNeoForgeVersion(project: Project): String {
        val mcVersion = project.properties["minecraft_version"]!! as String
        val mcVerSplit = mcVersion.split(".")

        val baseUrl = "https://maven.neoforged.net/releases/net/neoforged/neoforge"
        val html = try {
            URI(baseUrl).toURL().readText()
        } catch (_: Exception) {
            throw RuntimeException("Failed to fetch $baseUrl")
        }

        val regex = Regex("(\\d{2}.\\d{1,2}.\\d{1,3})(-beta|)")
        val versions = regex.findAll(html)
            .map { it.groupValues[0] }
            .filter {
                val split = it.split(".")
                split[0] == mcVerSplit[1] && split[1] == mcVerSplit[2]
            }
            .sortedBy {
                val split = it.split(".")
                if (split[2].contains("-beta")) {
                    split[2].replaceFirst("-beta", "").toInt() - 1
                } else {
                    split[2].toInt()
                }
            }
            .toList()

        return versions[versions.size - 1]
    }
}