import com.google.gson.JsonParser
import org.gradle.api.Plugin
import org.gradle.api.Project
import java.io.File
import java.net.URI
import java.util.*

//I think usable is ok
open class FetchVersionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        target.gradle.beforeProject {
            if (target.rootProject == target) {
                val prop = Properties()
                val theFile = File("gradle.properties")

                if (!theFile.exists()) {
                    return@beforeProject
                }

                if (target.gradle.startParameter.isOffline) {
                    return@beforeProject
                }

                val cacheFile = File(project.layout.buildDirectory.get().asFile, "dependency_sync.cache")
                if (!cacheFile.exists()) {
                    cacheFile.parentFile.mkdirs()
                    cacheFile.createNewFile()
                }

                prop.load(theFile.reader())

                val str = cacheFile.readText()
                if (str.isNotEmpty()) {
                    if (str == prop["minecraft_version"]) {
                        return@beforeProject
                    }
                }

                cacheFile.setWritable(true)
                cacheFile.writeText(prop["minecraft_version"]!! as String, Charsets.UTF_8)

                target.gradle.startParameter.isRefreshDependencies = true

                prop["fabric_version"] = getLatestModrinthVersion("fabric-api", target)
                prop["fabric_loader_version"] = getLatestFabricLoaderVersion()
                prop["neo_version"] = getLatestNeoForgeVersion(target)
                prop["cloth_config_version"] = getLatestModrinthVersion("cloth-config", target)!!.split("+")[0]
                prop["modmenu_version"] = getLatestModrinthVersion("modmenu", target)

                prop.store(theFile.writer(Charsets.UTF_8), "Generated by fetchVersions task")
            }
        }
    }

    fun getLatestModrinthVersion(modId: String, project: Project): String? {
        val apiUrl = "https://api.modrinth.com/v2/project/$modId/version"
        val json = JsonParser.parseReader(URI(apiUrl).toURL().openStream().reader()).asJsonArray

        return json
            .filter {
                it.asJsonObject["game_versions"].asJsonArray.any { v -> v.asString == project.properties["minecraft_version"]!! }
            }
            .maxByOrNull {
                it.asJsonObject["date_published"].asString
            }
            ?.asJsonObject
            ?.get("version_number")
            ?.asString
    }

    fun getLatestFabricLoaderVersion(): String? {
        val url = URI("https://meta.fabricmc.net/v2/versions/loader").toURL()
        val json = JsonParser.parseReader(url.openStream().reader()).asJsonArray

        return json.firstOrNull {
            it.asJsonObject["stable"].asBoolean
        }?.asJsonObject?.get("version")?.asString
    }

    fun getLatestNeoForgeVersion(project: Project): String {
        val mcVersion = project.properties["minecraft_version"]!! as String
        val target = mcVersion.split(".");

        val baseUrl = "https://maven.neoforged.net/api/maven/versions/releases/net/neoforged/neoforge"
        val html = try {
            URI(baseUrl).toURL().readText()
        } catch (_: Exception) {
            throw RuntimeException("Failed to fetch $baseUrl")
        }

        val list = JsonParser.parseString(html).asJsonObject["versions"].asJsonArray

        val regex = Regex("""(\d{2}\.\d+\.\d+(?:\.\d+)?)(?:-.*)?""")
        val versions = list.asList()
            .map { it.asString }
            .filter { regex.matches(it) }
            .filter {
                val split = it.split(".")
                split[0] == target[0] && split[1] == target[1]
            }
            .sortedBy {
                val split = it.split(".")
                val p3 = split[2].substringBefore("-").toIntOrNull() ?: 0
                val p4 = split.getOrNull(3)?.substringBefore("-")?.toIntOrNull() ?: 0
                p3 * 100 + p4
            }
            .toList()

        if (versions.isEmpty()) {
            throw RuntimeException("No NeoForge version found for $mcVersion")
        }

        return versions.last()
    }
}