package io.lijinhong11.titlechanger

import com.google.gson.JsonElement
import com.google.gson.JsonParser
import org.gradle.api.GradleException
import org.gradle.api.Plugin
import org.gradle.api.Project
import java.net.URI
import java.util.*

open class FetchVersionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        if (target != target.rootProject || target.gradle.startParameter.isOffline) {
            return
        }

        val propertiesFile = target.file("gradle.properties")
        if (!propertiesFile.exists()) {
            return
        }

        // Apply on the root project before any dependency declarations are evaluated.
        val minecraftVersion = target.findProperty("minecraft_version") as? String
            ?: throw GradleException("Missing minecraft_version property")
        val cacheFile = target.file("dependency_sync.cache")
        if (cacheFile.exists() && cacheFile.readText(Charsets.UTF_8).trim() == minecraftVersion) {
            return
        }

        // Resolve everything first: a failed request must not mark this version as synced.
        val versions = linkedMapOf(
            "minecraft_version" to minecraftVersion,
            "fabric_version" to getLatestModrinthVersion("fabric-api", target),
            "fabric_loader_version" to getLatestFabricLoaderVersion(),
            "neo_version" to getLatestNeoForgeVersion(target),
            "cloth_config_version" to getLatestModrinthVersion("cloth-config", target).substringBefore("+"),
            "modmenu_version" to getLatestModrinthVersion("modmenu", target),
            "placeholder_api_version" to getLatestModrinthVersion("placeholder-api", target)
        )

        val properties = Properties().apply {
            propertiesFile.reader(Charsets.UTF_8).use { load(it) }
            putAll(versions)
        }
        propertiesFile.writer(Charsets.UTF_8).use {
            properties.store(it, "Generated by fetch-version plugin")
        }

        // Gradle has already loaded gradle.properties, including a copy on each subproject.
        target.allprojects {
            versions.forEach { (name, version) -> extensions.extraProperties.set(name, version) }
        }
        cacheFile.writeText(minecraftVersion, Charsets.UTF_8)
        target.logger.lifecycle("Synchronized dependency versions for Minecraft $minecraftVersion")
    }

    fun getLatestModrinthVersion(modId: String, project: Project): String {
        val minecraftVersion = project.findProperty("minecraft_version") as String
        val json = readJson("https://api.modrinth.com/v2/project/$modId/version").asJsonArray

        return json
            .filter {
                it.asJsonObject["game_versions"].asJsonArray.any { v -> v.asString == minecraftVersion } &&
                        it.asJsonObject["loaders"].asJsonArray.any { loader -> loader.asString == "fabric" }
            }
            .maxByOrNull {
                it.asJsonObject["date_published"].asString
            }
            ?.asJsonObject
            ?.get("version_number")
            ?.asString
            ?: throw GradleException("No Fabric version of $modId found for Minecraft $minecraftVersion")
    }

    fun getLatestFabricLoaderVersion(): String {
        val json = readJson("https://meta.fabricmc.net/v2/versions/loader").asJsonArray

        return json.firstOrNull {
            it.asJsonObject["stable"].asBoolean
        }?.asJsonObject?.get("version")?.asString
            ?: throw GradleException("No stable Fabric Loader version found")
    }

    fun getLatestNeoForgeVersion(project: Project): String {
        val mcVersion = project.findProperty("minecraft_version") as String
        val parts = mcVersion.split(".").map {
            it.toIntOrNull() ?: throw GradleException("Unsupported Minecraft version for NeoForge: $mcVersion")
        }
        if (parts.size !in 2..3) {
            throw GradleException("Unsupported Minecraft version for NeoForge: $mcVersion")
        }
        // 1.21.1 -> 21.1.x; 26.2 -> 26.2.0.x; 26.1.2 -> 26.1.2.x.
        val prefix = if (parts[0] == 1) {
            listOf(parts[1], parts.getOrElse(2) { 0 })
        } else {
            listOf(parts[0], parts[1], parts.getOrElse(2) { 0 })
        }
        val list = readJson("https://maven.neoforged.net/api/maven/versions/releases/net/neoforged/neoforge")
            .asJsonObject["versions"].asJsonArray
        val regex = Regex("""\d+\.\d+\.\d+(?:\.\d+)?(?:-.*)?""")
        return list
            .map { it.asString }
            .filter { regex.matches(it) }
            .map { it to it.substringBefore("-").split(".").map(String::toInt) }
            .filter {
                it.second.size == prefix.size + 1 && it.second.take(prefix.size) == prefix
            }
            .maxWithOrNull(compareBy<Pair<String, List<Int>>> { it.second.last() }
                .thenBy { !it.first.contains("-") })
            ?.first
            ?: throw GradleException("No NeoForge version found for Minecraft $mcVersion")
    }

    protected open fun readJson(url: String): JsonElement {
        try {
            val connection = URI(url).toURL().openConnection().apply {
                connectTimeout = 15_000
                readTimeout = 30_000
                setRequestProperty("User-Agent", "TitleChanger-Next/fetch-version")
            }
            return connection.getInputStream().bufferedReader(Charsets.UTF_8).use {
                JsonParser.parseReader(it)
            }
        } catch (exception: Exception) {
            throw GradleException("Failed to fetch dependency versions from $url", exception)
        }
    }
}
